-- Migration: 001_init_watchlist_system.down.sql
-- Rollback script to drop all tables

-- Drop tables in reverse order (due to foreign key constraints)
DROP TABLE IF EXISTS AUDIT_LOG;
DROP TABLE IF EXISTS MATCHING_DETAILS;
DROP TABLE IF EXISTS MATCHING_RESULTS;
DROP TABLE IF EXISTS PROCESSING_LOG;
DROP TABLE IF EXISTS BATCH_PROCESSING;
DROP TABLE IF EXISTS SYSTEM_CONFIG;
DROP TABLE IF EXISTS MATCHING_CONFIG;
DROP TABLE IF EXISTS MASTER_LOCAL_BLACKLIST;
DROP TABLE IF EXISTS MASTER_WMD;
DROP TABLE IF EXISTS MASTER_TERORIS;
DROP TABLE IF EXISTS MASTER_NASABAH;
DROP TABLE IF EXISTS USER_SESSIONS;
DROP TABLE IF EXISTS USERS;